// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcprulruuufucyvthzxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjcHJ1bHJ1dXVmdWN5dnRoenh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjE5MzQsImV4cCI6MjA1OTU5NzkzNH0.ysb6wT7Eek2j97l0ELAYNysm0eAmr7UA34BtSdit9SM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);